# Auto-generated embedded languages data
# This file is auto-generated from config/languages.json
# Do not edit manually - run create_embedded_languages.py to regenerate

LANGUAGES_JSON = {
    "version": "1.0",
    "default_popular_limit": 12,
    "default_popular_languages": [
        "es",
        "fr",
        "de",
        "it",
        "pt-BR",
        "zh-Hans",
        "ja",
        "ar",
        "vi",
        "id",
        "tr",
        "az",
    ],
    "languages": {
        "sq": {"name": "Albanian", "popular": False},
        "ar": {
            "name": "Arabic",
            "popular": True,
            "sentence_endings": ["!", "؟", "…", "."],
        },
        "hy": {"name": "Armenian", "popular": False},
        "az": {
            "name": "Azerbaijani",
            "popular": True,
            "break_markers": ["və", "amma", "lakin", "beləliklə"],
        },
        "eu": {"name": "Basque", "popular": False},
        "be": {"name": "Belarusian", "popular": False},
        "bn": {"name": "Bengali", "popular": False},
        "bg": {"name": "Bulgarian", "popular": False},
        "ca": {"name": "Catalan", "popular": False},
        "zh-Hans": {
            "name": "Chinese (Simplified)",
            "popular": True,
            "sentence_endings": ["。", "！", "？", "……"],
        },
        "zh-Hant": {"name": "Chinese (Traditional)", "popular": False},
        "hr": {"name": "Croatian", "popular": False},
        "cs": {"name": "Czech", "popular": False},
        "da": {"name": "Danish", "popular": False},
        "nl": {"name": "Dutch", "popular": True},
        "en": {
            "name": "English",
            "popular": False,
            "break_markers": [
                "and",
                "but",
                "or",
                "so",
                "because",
                "however",
                "therefore",
                "although",
                "while",
                "since",
            ],
        },
        "et": {"name": "Estonian", "popular": False},
        "fa": {"name": "Persian", "popular": False},
        "fi": {"name": "Finnish", "popular": False},
        "fr": {"name": "French", "popular": True},
        "gl": {"name": "Galician", "popular": False},
        "ka": {"name": "Georgian", "popular": False},
        "de": {"name": "German", "popular": True},
        "el": {"name": "Greek", "popular": False},
        "gu": {"name": "Gujarati", "popular": False},
        "ha": {"name": "Hausa", "popular": False},
        "he": {"name": "Hebrew", "popular": False},
        "hi": {"name": "Hindi", "popular": True},
        "hu": {"name": "Hungarian", "popular": False},
        "is": {"name": "Icelandic", "popular": False},
        "ig": {"name": "Igbo", "popular": False},
        "id": {"name": "Indonesian", "popular": True},
        "ga": {"name": "Irish", "popular": False},
        "it": {"name": "Italian", "popular": True},
        "ja": {
            "name": "Japanese",
            "popular": True,
            "sentence_endings": ["。", "！", "？", "…"],
        },
        "kn": {"name": "Kannada", "popular": False},
        "kk": {"name": "Kazakh", "popular": False},
        "km": {"name": "Khmer", "popular": False},
        "ko": {
            "name": "Korean",
            "popular": True,
            "sentence_endings": ["다.", "요.", "죠.", "입니다."],
        },
        "ky": {"name": "Kyrgyz", "popular": False},
        "lo": {"name": "Lao", "popular": False},
        "lv": {"name": "Latvian", "popular": False},
        "lt": {"name": "Lithuanian", "popular": False},
        "mk": {"name": "Macedonian", "popular": False},
        "ml": {"name": "Malayalam", "popular": False},
        "ms": {"name": "Malay (Malaysia)", "popular": False},
        "mt": {"name": "Maltese", "popular": False},
        "mr": {"name": "Marathi", "popular": False},
        "mn": {"name": "Mongolian", "popular": False},
        "ne": {"name": "Nepali", "popular": False},
        "no": {"name": "Norwegian", "popular": False},
        "pl": {"name": "Polish", "popular": False},
        "pt-BR": {"name": "Portuguese (Brazil)", "popular": True},
        "pt-PT": {"name": "Portuguese (Portugal)", "popular": False},
        "ro": {"name": "Romanian", "popular": False},
        "ru": {"name": "Russian", "popular": True},
        "si": {"name": "Sinhala", "popular": False},
        "sk": {"name": "Slovak", "popular": False},
        "sl": {"name": "Slovenian", "popular": False},
        "so": {"name": "Somali", "popular": False},
        "es": {"name": "Spanish", "popular": True},
        "sr": {"name": "Serbian", "popular": False},
        "sw": {"name": "Swahili", "popular": False},
        "sv": {"name": "Swedish", "popular": False},
        "ta": {"name": "Tamil", "popular": False},
        "te": {"name": "Telugu", "popular": False},
        "th": {"name": "Thai", "popular": False},
        "tl": {"name": "Filipino", "popular": False},
        "tr": {
            "name": "Turkish",
            "popular": True,
            "break_markers": ["ve", "ama", "bu nedenle", "fakat"],
        },
        "tk": {"name": "Turkmen", "popular": False},
        "uk": {"name": "Ukrainian", "popular": False},
        "ur": {"name": "Urdu", "popular": False},
        "uz": {"name": "Uzbek", "popular": False},
        "vi": {
            "name": "Vietnamese",
            "popular": True,
            "break_markers": ["và", "nhưng", "do đó", "tuy nhiên"],
        },
        "cy": {"name": "Welsh", "popular": False},
        "xh": {"name": "Xhosa", "popular": False},
        "yo": {"name": "Yoruba", "popular": False},
        "zu": {"name": "Zulu", "popular": False},
    },
}


def get_embedded_languages():
    """Get the embedded language configuration"""
    return LANGUAGES_JSON
